export const DEFAULT_BILL_LAYOUT = [
  { id: "headerText", name: "Receipt Title", left: 10, top: 10, width: 380, height: 20, fontSize: 13, fontWeight: "normal", color: "#1f2937", align: "center", visible: true, text: "Bill Payment Receipt" },
  { id: "headerDate", name: "Receipt Month", left: 300, top: 10, width: 90, height: 20, fontSize: 11, fontWeight: "semibold", color: "#6b7280", align: "right", visible: true, text: "On Month" },
  
  { id: "schoolBox", name: "School Header Box", left: 10, top: 32, width: 380, height: 48, fontSize: 11, fontWeight: "normal", color: "#000000", align: "center", visible: true, border: true },
  { id: "schoolName", name: "School Name", left: 15, top: 35, width: 370, height: 24, fontSize: 17, fontWeight: "bold", color: "#000000", align: "center", visible: true, text: "NEW PROGRESSIVE PUBLIC SCHOOL" },
  { id: "schoolAddress", name: "School Address", left: 15, top: 57, width: 370, height: 20, fontSize: 13, fontWeight: "normal", color: "#000000", align: "center", visible: true, text: "Nauroo, Jehanabad" },
  
  { id: "studentBox", name: "Student Info Box", left: 10, top: 88, width: 380, height: 64, fontSize: 12, fontWeight: "normal", color: "#000000", align: "left", visible: true, border: true },
  { id: "studentName", name: "Student Name", left: 16, top: 92, width: 190, height: 18, fontSize: 12, fontWeight: "semibold", color: "#000000", align: "left", visible: true },
  { id: "studentClass", name: "Student Class", left: 210, top: 92, width: 170, height: 18, fontSize: 12, fontWeight: "semibold", color: "#000000", align: "left", visible: true },
  { id: "studentParent", name: "Student Parent", left: 16, top: 112, width: 190, height: 36, fontSize: 11, fontWeight: "normal", color: "#000000", align: "left", visible: true },
  { id: "studentAddress", name: "Student Address", left: 210, top: 112, width: 170, height: 36, fontSize: 11, fontWeight: "normal", color: "#000000", align: "left", visible: true },
  
  { id: "feesList", name: "Fees Breakdown", left: 10, top: 162, width: 380, height: 110, fontSize: 12, fontWeight: "normal", color: "#000000", align: "left", visible: true },
  { id: "qrCode", name: "UPI QR Code", left: 145, top: 180, width: 110, height: 115, fontSize: 10, fontWeight: "normal", color: "#6b7280", align: "center", visible: true },
  
  { id: "dividerLine", name: "Divider Line", left: 10, top: 300, width: 380, height: 10, fontSize: 12, fontWeight: "normal", color: "#9ca3af", align: "center", visible: true, text: "--------------------------------------------------------" },
  { id: "totalDues", name: "Total Dues", left: 10, top: 312, width: 380, height: 24, fontSize: 14, fontWeight: "bold", color: "#000000", align: "left", visible: true },
  
  { id: "notesBox", name: "Instructions Box", left: 10, top: 342, width: 380, height: 60, fontSize: 10, fontWeight: "normal", color: "#000000", align: "left", visible: true, border: true, text: "1. Fee Payment date is from 1st to 10th of every month.\n2. ₹50/- late fine if paid after due date.\n3. Admission may be canceled if not paid." },
  { id: "pageId", name: "Receipt Page ID", left: 300, top: 410, width: 90, height: 20, fontSize: 11, fontWeight: "semibold", color: "#374151", align: "right", visible: true },
];

export const PRESETS = {
  classic: [
    { id: "headerText", name: "Receipt Title", left: 10, top: 10, width: 380, height: 20, fontSize: 13, fontWeight: "normal", color: "#1f2937", align: "center", visible: true, text: "Bill Payment Receipt" },
    { id: "headerDate", name: "Receipt Month", left: 300, top: 10, width: 90, height: 20, fontSize: 11, fontWeight: "semibold", color: "#6b7280", align: "right", visible: true, text: "On Month" },
    { id: "schoolBox", name: "School Header Box", left: 10, top: 32, width: 380, height: 48, fontSize: 11, fontWeight: "normal", color: "#000000", align: "center", visible: true, border: true },
    { id: "schoolName", name: "School Name", left: 15, top: 35, width: 370, height: 24, fontSize: 17, fontWeight: "bold", color: "#000000", align: "center", visible: true, text: "NEW PROGRESSIVE PUBLIC SCHOOL" },
    { id: "schoolAddress", name: "School Address", left: 15, top: 57, width: 370, height: 20, fontSize: 13, fontWeight: "normal", color: "#000000", align: "center", visible: true, text: "Nauroo, Jehanabad" },
    { id: "studentBox", name: "Student Info Box", left: 10, top: 88, width: 380, height: 64, fontSize: 12, fontWeight: "normal", color: "#000000", align: "left", visible: true, border: true },
    { id: "studentName", name: "Student Name", left: 16, top: 92, width: 190, height: 18, fontSize: 12, fontWeight: "semibold", color: "#000000", align: "left", visible: true },
    { id: "studentClass", name: "Student Class", left: 210, top: 92, width: 170, height: 18, fontSize: 12, fontWeight: "semibold", color: "#000000", align: "left", visible: true },
    { id: "studentParent", name: "Student Parent", left: 16, top: 112, width: 190, height: 36, fontSize: 11, fontWeight: "normal", color: "#000000", align: "left", visible: true },
    { id: "studentAddress", name: "Student Address", left: 210, top: 112, width: 170, height: 36, fontSize: 11, fontWeight: "normal", color: "#000000", align: "left", visible: true },
    { id: "feesList", name: "Fees Breakdown", left: 10, top: 162, width: 380, height: 110, fontSize: 12, fontWeight: "normal", color: "#000000", align: "left", visible: true },
    { id: "qrCode", name: "UPI QR Code", left: 145, top: 180, width: 110, height: 115, fontSize: 10, fontWeight: "normal", color: "#6b7280", align: "center", visible: true },
    { id: "dividerLine", name: "Divider Line", left: 10, top: 300, width: 380, height: 10, fontSize: 12, fontWeight: "normal", color: "#9ca3af", align: "center", visible: true, text: "--------------------------------------------------------" },
    { id: "totalDues", name: "Total Dues", left: 10, top: 312, width: 380, height: 24, fontSize: 14, fontWeight: "bold", color: "#000000", align: "left", visible: true },
    { id: "notesBox", name: "Instructions Box", left: 10, top: 342, width: 380, height: 60, fontSize: 10, fontWeight: "normal", color: "#000000", align: "left", visible: true, border: true, text: "1. Fee Payment date is from 1st to 10th of every month.\n2. ₹50/- late fine if paid after due date.\n3. Admission may be canceled if not paid." },
    { id: "pageId", name: "Receipt Page ID", left: 300, top: 410, width: 90, height: 20, fontSize: 11, fontWeight: "semibold", color: "#374151", align: "right", visible: true },
  ],
  modern: [
    { id: "headerText", name: "Receipt Title", left: 10, top: 10, width: 380, height: 20, fontSize: 12, fontWeight: "bold", color: "#ea580c", align: "left", visible: true, text: "BILL PAYMENT RECEIPT" },
    { id: "headerDate", name: "Receipt Month", left: 300, top: 10, width: 90, height: 20, fontSize: 11, fontWeight: "normal", color: "#6b7280", align: "right", visible: true, text: "On Month" },
    { id: "schoolBox", name: "School Header Box", left: 10, top: 32, width: 380, height: 48, fontSize: 11, fontWeight: "normal", color: "#ea580c", align: "center", visible: true, border: false },
    { id: "schoolName", name: "School Name", left: 10, top: 32, width: 380, height: 24, fontSize: 18, fontWeight: "extrabold", color: "#ea580c", align: "left", visible: true, text: "NEW PROGRESSIVE PUBLIC SCHOOL" },
    { id: "schoolAddress", name: "School Address", left: 10, top: 56, width: 380, height: 20, fontSize: 12, fontWeight: "semibold", color: "#6b7280", align: "left", visible: true, text: "Nauroo, Jehanabad, Bihar" },
    { id: "studentBox", name: "Student Info Box", left: 10, top: 82, width: 380, height: 75, fontSize: 12, fontWeight: "normal", color: "#f3f4f6", align: "left", visible: true, border: false },
    { id: "studentName", name: "Student Name", left: 15, top: 86, width: 180, height: 18, fontSize: 12, fontWeight: "bold", color: "#1f2937", align: "left", visible: true },
    { id: "studentClass", name: "Student Class", left: 205, top: 86, width: 180, height: 18, fontSize: 12, fontWeight: "bold", color: "#1f2937", align: "left", visible: true },
    { id: "studentParent", name: "Student Parent", left: 15, top: 108, width: 180, height: 36, fontSize: 11, fontWeight: "normal", color: "#4b5563", align: "left", visible: true },
    { id: "studentAddress", name: "Student Address", left: 205, top: 108, width: 180, height: 36, fontSize: 11, fontWeight: "normal", color: "#4b5563", align: "left", visible: true },
    { id: "feesList", name: "Fees Breakdown", left: 10, top: 165, width: 380, height: 110, fontSize: 12, fontWeight: "normal", color: "#374151", align: "left", visible: true },
    { id: "qrCode", name: "UPI QR Code", left: 145, top: 175, width: 110, height: 115, fontSize: 9, fontWeight: "normal", color: "#ea580c", align: "center", visible: true },
    { id: "dividerLine", name: "Divider Line", left: 10, top: 295, width: 380, height: 10, fontSize: 12, fontWeight: "normal", color: "#ea580c", align: "center", visible: true, text: "--------------------------------------------------------" },
    { id: "totalDues", name: "Total Dues", left: 10, top: 310, width: 380, height: 24, fontSize: 15, fontWeight: "extrabold", color: "#ea580c", align: "left", visible: true },
    { id: "notesBox", name: "Instructions Box", left: 10, top: 340, width: 380, height: 60, fontSize: 9, fontWeight: "normal", color: "#4b5563", align: "left", visible: true, border: false, text: "• Fee Payment date is from 1st to 10th of every month.\n• ₹50/- late fine if paid after due date.\n• Admission may be canceled if not paid." },
    { id: "pageId", name: "Receipt Page ID", left: 300, top: 410, width: 90, height: 20, fontSize: 11, fontWeight: "bold", color: "#ea580c", align: "right", visible: true },
  ],
  compact: [
    { id: "headerText", name: "Receipt Title", left: 10, top: 5, width: 380, height: 16, fontSize: 11, fontWeight: "normal", color: "#374151", align: "center", visible: true, text: "Fee Receipt" },
    { id: "headerDate", name: "Receipt Month", left: 300, top: 5, width: 90, height: 16, fontSize: 10, fontWeight: "normal", color: "#6b7280", align: "right", visible: true, text: "On Month" },
    { id: "schoolBox", name: "School Header Box", left: 10, top: 23, width: 380, height: 35, fontSize: 10, fontWeight: "normal", color: "#000000", align: "center", visible: true, border: true },
    { id: "schoolName", name: "School Name", left: 15, top: 25, width: 370, height: 18, fontSize: 14, fontWeight: "bold", color: "#000000", align: "center", visible: true, text: "NEW PROGRESSIVE PUBLIC SCHOOL" },
    { id: "schoolAddress", name: "School Address", left: 15, top: 41, width: 370, height: 16, fontSize: 11, fontWeight: "normal", color: "#000000", align: "center", visible: true, text: "Nauroo, Jehanabad" },
    { id: "studentBox", name: "Student Info Box", left: 10, top: 62, width: 380, height: 50, fontSize: 11, fontWeight: "normal", color: "#000000", align: "left", visible: true, border: true },
    { id: "studentName", name: "Student Name", left: 16, top: 65, width: 190, height: 16, fontSize: 11, fontWeight: "semibold", color: "#000000", align: "left", visible: true },
    { id: "studentClass", name: "Student Class", left: 210, top: 65, width: 170, height: 16, fontSize: 11, fontWeight: "semibold", color: "#000000", align: "left", visible: true },
    { id: "studentParent", name: "Student Parent", left: 16, top: 81, width: 190, height: 28, fontSize: 10, fontWeight: "normal", color: "#000000", align: "left", visible: true },
    { id: "studentAddress", name: "Student Address", left: 210, top: 81, width: 170, height: 28, fontSize: 10, fontWeight: "normal", color: "#000000", align: "left", visible: true },
    { id: "feesList", name: "Fees Breakdown", left: 10, top: 118, width: 380, height: 100, fontSize: 11, fontWeight: "normal", color: "#000000", align: "left", visible: true },
    { id: "qrCode", name: "UPI QR Code", left: 155, top: 130, width: 90, height: 95, fontSize: 9, fontWeight: "normal", color: "#6b7280", align: "center", visible: true },
    { id: "dividerLine", name: "Divider Line", left: 10, top: 222, width: 380, height: 10, fontSize: 11, fontWeight: "normal", color: "#9ca3af", align: "center", visible: true, text: "--------------------------------------------------------" },
    { id: "totalDues", name: "Total Dues", left: 10, top: 234, width: 380, height: 20, fontSize: 13, fontWeight: "bold", color: "#000000", align: "left", visible: true },
    { id: "notesBox", name: "Instructions Box", left: 10, top: 258, width: 380, height: 48, fontSize: 9, fontWeight: "normal", color: "#000000", align: "left", visible: true, border: true, text: "1. Fee Payment: 1st to 10th of every month.\n2. ₹50/- late fine if paid after due date." },
    { id: "pageId", name: "Receipt Page ID", left: 300, top: 312, width: 90, height: 16, fontSize: 10, fontWeight: "semibold", color: "#374151", align: "right", visible: true },
  ]
};
