import "./globals.css";
import { Toaster } from "react-hot-toast";
import StickyMenu from "@/components/StickyMenu";

export const metadata = {
  title: "NPPS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <StickyMenu />
        {children}
        <Toaster
          position="bottom-left"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
